### ISSUE TITLE
Davinci Resolve 18

### ISSUE THREAD

**Issue by adrienlabigne** [autopkg/timsutton-recipes#103]
Hi !

Did you plan to make a receipt for the last release of Davinci Resolve, the 18th ?
Or the receipt for 17 download the 18 (I dont think so, or I would have already downloaded it).

Thanks

**Comment by timsutton** [comment]
I don't have any specific plans to do 18, no – I haven't had to support a Resolve installation via Munki in a long time. If someone were to dupe the `DaVinciResolve17` recipe I have in this repo and make the appropriate adjustments I'd be happy to accept a PR for it, though.

**Comment by peterkelm** [comment]
Just FYI: The existing recipe works great also for version 18 using minimal edits to the usual autopkg override:

1) Change the `PRODUCT_NAME_PATTERN` in the override file to `^DaVinci Resolve (?P&lt;version&gt;18(\.\d+)*)( Update)*$`. 
2) Update `17` to `18` in the `description` and the `display_name` key strings… 

Important: Don't mess with the `ParentRecipe` and `ParentRecipeTrustInfo` data! The parent recipes will just have the "17" in their names…

And that's it.

FYI: I also changed the recipe identifier in the override file to `local.munki.DaVinciResolve18` so that I get a separate autopkg cache folder for it… but that wouldn't be necessary technically.

**Comment by timsutton** [comment]
@peterkelm Want to test out these? I just made those changes here: https://github.com/autopkg/timsutton-recipes/pull/106 but don't currently have a great way to test that the installation/uninstall works properly.

**Comment by timsutton** [comment]
Finally got around to looking at PRs in this repo and I just merged #106. I'll close this issue for now, feel free to re-open if it's not resolved!
